version: '3.4'

services:
  app:
    image: golang:1.18
    ports:
      - 1337:${APP_PORT}
    volumes:
      - .:/go/src/app:z
    working_dir: /go/src/app
    command: sh -c "go run ./cmd/migrate/main.go && go run ./cmd/beetroot/main.go"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_PORT: ${APP_PORT}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PAYLOAD_BYTE_LIMIT: ${PAYLOAD_BYTE_LIMIT}
  postgres:
    # TODO: Can we specify UTC timezone for postgres?
    ports:
      - ${POSTGRES_PORT}:5432
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      # TODO: can we get rid of the constant pings?
      test: ["CMD-SHELL", "pg_isready -U dev"]
      timeout: 1s
      interval: 5s
      retries: 5
