name: deploy

on:
  push:
    branches: [master, uat, qa, workflow-test]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker-compose run app go test ./...
